services:
  - type: web
    name: activity-in-english-ia
    runtime: python
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers=1 --threads=4 --timeout=180
    pythonVersion: "3.11.4"